import { Post } from '../types';

export const mockPosts: Post[] = [
  {
    id: 1,
    title_az: 'Milli Aviasiya Akademiyasının təşkilatçılığı ilə hazırlanan "Research and Updates on the Use of Artificial Intelligence in Drone Technology" kitabı Springer Nature nəşriyyatında dərc olunub',
    title_en: 'The book "Research and Updates on the Use of Artificial Intelligence in Drone Technology" prepared by the National Aviation Academy was published by Springer Nature',
    slug: 'research-ai-drone-technology',
    category: 'news',
    cover_image: 'https://images.pexels.com/photos/442150/plane-aircraft-take-off-sky-442150.jpeg?auto=compress&cs=tinysrgb&w=400',
    content_az: 'Milli Aviasiya Akademiyasının təşkilatçılığı ilə hazırlanan "Research and Updates on the Use of Artificial Intelligence in Drone Technology" adlı kitab Springer Nature nəşriyyatında dərc olunub.',
    content_en: 'The book titled "Research and Updates on the Use of Artificial Intelligence in Drone Technology" prepared by the National Aviation Academy was published by Springer Nature.',
    status: 'active',
    publish_status: 'published',
    author: 'snovruzlu',
    sharing_time: '2026-11-06T10:19:00Z',
    created_at: '2026-11-06T10:19:00Z',
    updated_at: '2026-11-06T10:19:00Z',
  },
  {
    id: 2,
    title_az: 'Milli Aviasiya Akademiyasında təhsil alan tələbələr üçün ICAO və IATA təlimləri',
    title_en: 'ICAO and IATA training for students studying at the National Aviation Academy',
    slug: 'icao-iata-training-students',
    category: 'announcement',
    cover_image: 'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=400',
    content_az: 'Akademiyada təhsil alan tələbələr üçün beynəlxalq aviasiya standartları üzrə təlimlər keçirilir.',
    content_en: 'International aviation standards training is conducted for students at the Academy.',
    status: 'active',
    publish_status: 'published',
    author: 'snovruzlu',
    sharing_time: '2026-11-06T10:19:00Z',
    created_at: '2026-11-06T10:19:00Z',
    updated_at: '2026-11-06T10:19:00Z',
  },
  {
    id: 3,
    title_az: 'Milli Aviasiya Akademiyasının təşkilatçılığı ilə "Pilotazz Sistemləri: Suni İntellekt, Dizayn və Səmərəlilik" kitabı',
    title_en: 'Book "Piloting Systems: Artificial Intelligence, Design and Efficiency" organized by the National Aviation Academy',
    slug: 'piloting-systems-book',
    category: 'news',
    cover_image: 'https://images.pexels.com/photos/163792/model-planes-airplanes-miniature-toy-163792.jpeg?auto=compress&cs=tinysrgb&w=400',
    content_az: 'Akademiya tərəfindən hazırlanan pilotazz sistemləri haqqında əsas əsər nəşr olunub.',
    content_en: 'A major work on piloting systems prepared by the Academy has been published.',
    status: 'active',
    publish_status: 'published',
    author: 'snovruzlu',
    sharing_time: '2026-11-06T10:19:00Z',
    created_at: '2026-11-06T10:19:00Z',
    updated_at: '2026-11-06T10:19:00Z',
  },
  {
    id: 4,
    title_az: 'Milli Aviasiya Akademiyasında yeni aviasiya laboratoriyasının açılışı',
    title_en: 'Opening of new aviation laboratory at National Aviation Academy',
    slug: 'new-aviation-laboratory-opening',
    category: 'news',
    cover_image: 'https://images.pexels.com/photos/256381/pexels-photo-256381.jpeg?auto=compress&cs=tinysrgb&w=400',
    content_az: 'Akademiyada müasir avadanlıqlarla təchiz olunmuş yeni aviasiya laboratoriyası fəaliyyətə başlayıb.',
    content_en: 'A new aviation laboratory equipped with modern equipment has started operating at the Academy.',
    status: 'active',
    publish_status: 'published',
    author: 'snovruzlu',
    sharing_time: '2026-11-05T14:30:00Z',
    created_at: '2026-11-05T14:30:00Z',
    updated_at: '2026-11-05T14:30:00Z',
  },
  {
    id:5,
    title_az: 'Beynəlxalq Aviasiya Konfransı 2026 - Qatılım üçün son müraciət tarixi',
    title_en: 'International Aviation Conference 2026 - Final application deadline',
    slug: 'international-aviation-conference-2026',
    category: 'announcement',
    cover_image: 'https://images.pexels.com/photos/27406/pexels-photo-27406.jpg?auto=compress&cs=tinysrgb&w=400',
    content_az: 'Beynəlxalq Aviasiya Konfransına qatılmaq üçün müraciətlər 15 noyabr tarixinə qədər qəbul olunur.',
    content_en: 'Applications to participate in the International Aviation Conference are accepted until November 15.',
    status: 'active',
    publish_status: 'published',
    author: 'snovruzlu',
    sharing_time: '2026-11-04T09:15:00Z',
    created_at: '2026-11-04T09:15:00Z',
    updated_at: '2026-11-04T09:15:00Z',
  },
  {
    id:6,
    title_az: 'Aviasiya mühəndisliyi üzrə yeni tədris proqramı təqdim olundu',
    title_en: 'New aviation engineering curriculum introduced',
    slug: 'new-aviation-engineering-curriculum',
    category: 'news',
    cover_image: 'https://images.pexels.com/photos/159306/construction-site-build-construction-work-159306.jpeg?auto=compress&cs=tinysrgb&w=400',
    content_az: 'Akademiya aviasiya mühəndisliyi ixtisası üçün yenilənmiş tədris proqramını təqdim etdi.',
    content_en: 'The Academy has introduced an updated curriculum for the aviation engineering specialty.',
    status: 'active',
    publish_status: 'published',
    author: 'snovruzlu',
    sharing_time: '2026-11-03T16:45:00Z',
    created_at: '2026-11-03T16:45:00Z',
    updated_at: '2026-11-03T16:45:00Z',
  },
  {
    id: 7,
    title_az: 'Tələbələr üçün hava nəqliyyatı idarəetməsi seminarı',
    title_en: 'Air traffic management seminar for students',
    slug: 'air-traffic-management-seminar',
    category: 'announcement',
    cover_image: 'https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg?auto=compress&cs=tinysrgb&w=400',
    content_az: 'Hava nəqliyyatı idarəetməsi üzrə təcrübəli mütəxəssislər tərəfindən tələbələr üçün seminar təşkil olunur.',
    content_en: 'A seminar for students is organized by experienced specialists in air traffic management.',
    status: 'active',
    publish_status: 'published',
    author: 'snovruzlu',
    sharing_time: '2026-11-02T11:20:00Z',
    created_at: '2026-11-02T11:20:00Z',
    updated_at: '2026-11-02T11:20:00Z',
  },

];